using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace aGrouponClasses.Payment {
    public class PaymentAgentBeelineKg :IPayment{
        public string PaymentType
        {
            get {return "Beeline Payment"; }
        }

        private decimal _amountToBePaid;
        public decimal AmountToBePaid
        {
            get { return _amountToBePaid; }
        }

        public void SetAmountToBePaid(decimal Amount)
        {
            _amountToBePaid = Amount; 
        }

        private string _errorMessage;
        public string StatusMessage
        {
            get { return _errorMessage; }
            set { _errorMessage = value; }
        }

        private string _paymentCode;
        public string PaymentCode {
            get { return _paymentCode; }
        }

        public bool MakePayment()
        {
            _errorMessage = "Payment Made Successfully";
            _paymentCode = "0000"; // This is the code to be generated by Mobile Company
            return true;
        }
    }
}
